/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SpotifyLogin {
        /**
          * The first name
         */
        "clientId": string;
        /**
          * The last name
         */
        "redirectUri": string;
        /**
          * The middle name
         */
        "scope": string;
    }
}
declare global {
    interface HTMLSpotifyLoginElement extends Components.SpotifyLogin, HTMLStencilElement {
    }
    var HTMLSpotifyLoginElement: {
        prototype: HTMLSpotifyLoginElement;
        new (): HTMLSpotifyLoginElement;
    };
    interface HTMLElementTagNameMap {
        "spotify-login": HTMLSpotifyLoginElement;
    }
}
declare namespace LocalJSX {
    interface SpotifyLogin {
        /**
          * The first name
         */
        "clientId"?: string;
        "onCompleted"?: (event: CustomEvent<any>) => void;
        "onFail"?: (event: CustomEvent<any>) => void;
        /**
          * The last name
         */
        "redirectUri"?: string;
        /**
          * The middle name
         */
        "scope"?: string;
    }
    interface IntrinsicElements {
        "spotify-login": SpotifyLogin;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "spotify-login": LocalJSX.SpotifyLogin & JSXBase.HTMLAttributes<HTMLSpotifyLoginElement>;
        }
    }
}
